/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.alex.calculadora;

/**
 *
 * @author alexf
 */
public class Calculadora extends javax.swing.JFrame {

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
    }
    //variável para pegar valor exibido na tela
    String temp = "", oper = "";
    float valorInicial = 0;
    float valorFinal = 0;
    float valorTotal = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        lblDigitacao = new javax.swing.JLabel();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btnDiv = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btnMulti = new javax.swing.JButton();
        btnVirg = new javax.swing.JButton();
        btnZero = new javax.swing.JButton();
        btnIgual = new javax.swing.JButton();
        btnMais = new javax.swing.JButton();
        btnMenos = new javax.swing.JButton();
        lblVisor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OMFSystem - Calculadora");
        setBackground(new java.awt.Color(204, 255, 204));
        setResizable(false);

        lblDigitacao.setBackground(new java.awt.Color(255, 255, 255));
        lblDigitacao.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblDigitacao.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDigitacao.setText("0");

        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btnDel.setText("DEL");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btnDiv.setText("÷");
        btnDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivActionPerformed(evt);
            }
        });

        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btnMulti.setText("x");
        btnMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiActionPerformed(evt);
            }
        });

        btnVirg.setText(",");
        btnVirg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVirgActionPerformed(evt);
            }
        });

        btnZero.setText("0");
        btnZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZeroActionPerformed(evt);
            }
        });

        btnIgual.setText("=");
        btnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIgualActionPerformed(evt);
            }
        });

        btnMais.setText("+");
        btnMais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaisActionPerformed(evt);
            }
        });

        btnMenos.setText("-");
        btnMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenosActionPerformed(evt);
            }
        });

        lblVisor.setBackground(new java.awt.Color(255, 255, 255));
        lblVisor.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblVisor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblVisor, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btnVirg, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(btnZero, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(btnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(btnMais, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblDigitacao, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(lblVisor, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(lblDigitacao, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(btnDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(btnMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(btnMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMais, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnVirg, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnZero, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>

    private void btnZeroActionPerformed(java.awt.event.ActionEvent evt) {
        if (!lblDigitacao.getText().equals("0")) {
            PegaValor();
            lblDigitacao.setText(temp + "0");
        } else {
            PegaValor();
            lblDigitacao.setText("0");
        }
    }

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {

        if (((lblDigitacao.getText().equals("0") || lblDigitacao.getText().equals("")) && valorTotal == 0)) {
            PegaValor();
            lblDigitacao.setText("");
            lblDigitacao.setText("1");

        } else if (valorTotal != 0) {
            PegaValor();
            lblDigitacao.setText(temp + "1");

        } else if (valorTotal == 0) {
            PegaValor();
            lblDigitacao.setText("");
            lblDigitacao.setText(temp + "1");
        }

    }

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {
        if (((lblDigitacao.getText().equals("0") || lblDigitacao.getText().equals("")) && valorTotal == 0)) {
            PegaValor();
            lblDigitacao.setText("");
            lblDigitacao.setText("2");

        } else if (valorTotal != 0) {
            PegaValor();
            lblDigitacao.setText(temp + "2");

        } else if (valorTotal == 0) {
            PegaValor();
            lblDigitacao.setText("");
            lblDigitacao.setText(temp + "2");
        }
    }

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {
        if (((lblDigitacao.getText().equals("0") || lblDigitacao.getText().equals("")) && valorTotal == 0)) {
            PegaValor();
            lblDigitacao.setText("");
            lblDigitacao.setText("3");

        } else if (valorTotal != 0) {
            PegaValor();
            lblDigitacao.setText(temp + "3");

        } else if (valorTotal == 0) {
            PegaValor();
            lblDigitacao.setText("");
            lblDigitacao.setText(temp + "3");
        }
    }

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {
        if (((lblDigitacao.getText().equals("0") || lblDigitacao.getText().equals("")) && valorTotal == 0)) {
            PegaValor();
            lblDigitacao.setText("");
            lblDigitacao.setText("4");

        } else if (valorTotal != 0) {
            PegaValor();
            lblDigitacao.setText(temp + "4");

        } else if (valorTotal == 0) {
            PegaValor();
            lblDigitacao.setText("");
            lblDigitacao.setText(temp + "4");
        }
    }

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {
        if (((lblDigitacao.getText().equals("0") || lblDigitacao.getText().equals("")) && valorTotal == 0)) {
            PegaValor();
            lblDigitacao.setText("");
            lblDigitacao.setText("5");

        } else if (valorTotal != 0) {
            PegaValor();
            lblDigitacao.setText(temp + "5");

        } else if (valorTotal == 0) {
            PegaValor();
            lblDigitacao.setText("");
            lblDigitacao.setText(temp + "5");
        }
    }

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {
        if (((lblDigitacao.getText().equals("0") || lblDigitacao.getText().equals("")) && valorTotal == 0)) {
            PegaValor();
            lblDigitacao.setText("");
            lblDigitacao.setText("6");

        } else if (valorTotal != 0) {
            PegaValor();
            lblDigitacao.setText(temp + "6");

        } else if (valorTotal == 0) {
            PegaValor();
            lblDigitacao.setText("");
            lblDigitacao.setText(temp + "6");
        }
    }

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {
        if (((lblDigitacao.getText().equals("0") || lblDigitacao.getText().equals("")) && valorTotal == 0)) {
            PegaValor();
            lblDigitacao.setText("");
            lblDigitacao.setText("7");

        } else if (valorTotal != 0) {
            PegaValor();
            lblDigitacao.setText(temp + "7");

        } else if (valorTotal == 0) {
            PegaValor();
            lblDigitacao.setText("");
            lblDigitacao.setText(temp + "7");
        }
    }

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {
        if (((lblDigitacao.getText().equals("0") || lblDigitacao.getText().equals("")) && valorTotal == 0)) {
            PegaValor();
            lblDigitacao.setText("");
            lblDigitacao.setText("8");

        } else if (valorTotal != 0) {
            PegaValor();
            lblDigitacao.setText(temp + "8");

        } else if (valorTotal == 0) {
            PegaValor();
            lblDigitacao.setText("");
            lblDigitacao.setText(temp + "8");
        }
    }

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {
        if (((lblDigitacao.getText().equals("0") || lblDigitacao.getText().equals("")) && valorTotal == 0)) {
            PegaValor();
            lblDigitacao.setText("");
            lblDigitacao.setText("9");

        } else if (valorTotal != 0) {
            PegaValor();
            lblDigitacao.setText(temp + "9");

        } else if (valorTotal == 0) {
            PegaValor();
            lblDigitacao.setText("");
            lblDigitacao.setText(temp + "9");
        }
    }

    private void btnMaisActionPerformed(java.awt.event.ActionEvent evt) {
        if (valorInicial == 0 && !lblDigitacao.getText().equals("0")) {
            valorInicial = Float.parseFloat(lblDigitacao.getText());
            lblVisor.setText(String.valueOf(valorInicial) + " + ");
            oper = "+";
            temp = "";
            lblDigitacao.setText("");
        } else if (valorTotal != 0 && !lblDigitacao.getText().equals("")) {
            valorInicial = Float.parseFloat(lblDigitacao.getText());
            valorTotal = 0;
            valorFinal = 0;
            temp = "";
            oper = "+";
            lblVisor.setText(lblDigitacao.getText() + " + ");
            lblDigitacao.setText("");
        } else if (!lblDigitacao.getText().equals("") && !oper.equals("")) {
            Operacao();

        }
    }

    private void btnMenosActionPerformed(java.awt.event.ActionEvent evt) {
        if (valorInicial == 0 && !lblDigitacao.getText().equals("") && !lblDigitacao.getText().equals("0")) {
            valorInicial = Float.parseFloat(lblDigitacao.getText());
            lblVisor.setText(String.valueOf(valorInicial) + " - ");
            oper = "-";
            temp = "";
            lblDigitacao.setText("");
        } else if (valorTotal != 0 && !lblDigitacao.getText().equals("") && !lblDigitacao.getText().equals("0")) {
            valorInicial = Float.parseFloat(lblDigitacao.getText());
            valorTotal = 0;
            valorFinal = 0;
            temp = "";
            oper = "-";
            lblVisor.setText(lblDigitacao.getText() + " - ");
            lblDigitacao.setText("");
        } else if (!lblDigitacao.getText().equals("") && !lblDigitacao.getText().equals("0") && !oper.equals("") && valorInicial != 0) {
            Operacao();

        }
    }

    private void btnMultiActionPerformed(java.awt.event.ActionEvent evt) {
        if (valorInicial == 0 && !lblDigitacao.getText().equals("") && !lblDigitacao.getText().equals("0")) {
            valorInicial = Float.parseFloat(lblDigitacao.getText());
            lblVisor.setText(String.valueOf(valorInicial) + " * ");
            oper = "*";
            temp = "";
            lblDigitacao.setText("");
        } else if (valorTotal != 0 && !lblDigitacao.getText().equals("") && !lblDigitacao.getText().equals("0")) {
            valorInicial = Float.parseFloat(lblDigitacao.getText());
            valorTotal = 0;
            valorFinal = 0;
            temp = "";
            oper = "*";
            lblVisor.setText(lblDigitacao.getText() + " * ");
            lblDigitacao.setText("");
        } else if (!lblDigitacao.getText().equals("") && !lblDigitacao.getText().equals("0") && !oper.equals("") && valorInicial != 0) {
            Operacao();

        }
    }

    private void btnDivActionPerformed(java.awt.event.ActionEvent evt) {
        if (valorInicial == 0 && !lblDigitacao.getText().equals("") && !lblDigitacao.getText().equals("0")) {
            valorInicial = Float.parseFloat(lblDigitacao.getText());
            lblVisor.setText(String.valueOf(valorInicial) + " ÷ ");
            oper = "÷";
            temp = "";
            lblDigitacao.setText("");
        } else if (valorTotal != 0 && !lblDigitacao.getText().equals("") && !lblDigitacao.getText().equals("0")) {
            valorInicial = Float.parseFloat(lblDigitacao.getText());
            valorTotal = 0;
            valorFinal = 0;
            temp = "";
            oper = "÷";
            lblVisor.setText(lblDigitacao.getText() + " ÷ ");
            lblDigitacao.setText("");
        } else if (!lblDigitacao.getText().equals("") && !lblDigitacao.getText().equals("0") && !oper.equals("") && valorInicial != 0) {
            Operacao();

        }
    }

    private void btnIgualActionPerformed(java.awt.event.ActionEvent evt) {

        if (valorInicial >= 0 && valorFinal >= 0) {
            valorFinal = Float.parseFloat(lblDigitacao.getText());
            lblVisor.setText(String.valueOf(valorInicial + " " + oper + " " + valorFinal));
            lblDigitacao.setText("");
            if (valorInicial >= 0 && valorFinal >= 0) {
                switch (oper) {
                    case "+":
                        valorTotal = valorInicial + valorFinal;
                        break;
                    case "-":
                        valorTotal = valorInicial - valorFinal;
                        break;
                    case "*":
                        valorTotal = valorInicial * valorFinal;
                        break;
                    case "÷":
                        valorTotal = valorInicial / valorFinal;
                        break;
                    default:
                        break;
                }
                lblDigitacao.setText(String.valueOf(valorTotal));
                valorFinal = 0;
                valorInicial = 0;
            }

            temp = "";
        }

    }
//apaga o ultimo valor e caso seja ultimo apaga valor de todas as variáveis
    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {
        if (!lblDigitacao.getText().equals("")) {
            LimpaUltimoValor();
            lblDigitacao.setText(temp);
        }
        if (lblDigitacao.getText().equals("")) {
            LimpaCampos();
            lblDigitacao.setText("0");
        }

    }

    private void btnVirgActionPerformed(java.awt.event.ActionEvent evt) {

        if (!lblDigitacao.getText().contains(".")) {
            lblDigitacao.setText(lblDigitacao.getText() + ".");
        }


    }
    //pega valor atual na tela
    public void PegaValor() {
        temp = lblDigitacao.getText();
    }

    public void Operacao() {
        valorFinal = Float.parseFloat(lblDigitacao.getText());
        lblVisor.setText(String.valueOf(valorInicial + " " + oper + " " + valorFinal));
        lblDigitacao.setText("");
        if (valorInicial != 0 && valorFinal != 0) {
            switch (oper) {
                case "+":
                    valorTotal = valorInicial + valorFinal;
                    break;
                case "-":
                    valorTotal = valorInicial - valorFinal;
                    break;
                case "*":
                    valorTotal = valorInicial * valorFinal;
                    break;
                case "÷":
                    valorTotal = valorInicial / valorFinal;
                    break;
                default:
                    break;
            }
            lblDigitacao.setText(String.valueOf(valorTotal));
            valorFinal = 0;
            valorInicial = 0;
        }

    }

    //apaga ultimo valor na tela
    public void LimpaUltimoValor() {
        PegaValor();
        if (temp.length() > 0) {
            temp = temp.substring(0, temp.length() - 1);
        }
    }

    //apaga campos
    public void LimpaCampos() {
        lblDigitacao.setText("0");
        lblVisor.setText("");
        temp = "";
        oper = "";
        valorFinal = 0;
        valorInicial = 0;
        valorTotal = 0;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnDiv;
    private javax.swing.JButton btnIgual;
    private javax.swing.JButton btnMais;
    private javax.swing.JButton btnMenos;
    private javax.swing.JButton btnMulti;
    private javax.swing.JButton btnVirg;
    private javax.swing.JButton btnZero;
    private javax.swing.JLabel lblDigitacao;
    private javax.swing.JLabel lblVisor;
    // End of variables declaration
}
